### ISSUE TITLE
Stable NuGet release

### ISSUE THREAD

**Issue by pouladpld** [JuergenGutsch/graphql-aspnetcore#20]
Hi
I see two issues tagged as `bug` here. Are those the reasons for not having a stable release?

Please let me know what stops a stable release to nuget. I'd like to help.

**Comment by JuergenGutsch** [comment]
Hi @pouladpld, 
You already helped a lot 👍 Many thanks for that.
It is mostly about time, besides of work, family, side projects, blog, leading a user group, etc. :-)
I'm going to check the #16 tonight (CET). The #6 is fixed when I merge the develop to master, because the working build script is on develop.
Maybe you also can check the #16, if you have some time left :-)

**Comment by JuergenGutsch** [comment]
I just published a version to NuGet
