### ISSUE TITLE
IQueryable support

### ISSUE THREAD

**Issue by snebjorn** [JuergenGutsch/graphql-aspnetcore#21]
First off I'm really impressed with how easy it was to get setup. Everything is done the "aspnetcore" way, and the graphiql addition... I love it!

But I found this library https://github.com/ckimes89/graphql-net that makes generating a schema and querying against it really really easy.
So I was wondering if some collaboration was possible :)

I mean `services.AddGraphQl(schema => schema.AddType<Book>().AddAllFields());` would be a dream come true :D

**Comment by JuergenGutsch** [comment]
Hi @snebjorn,
Many thanks for this proposal. You are right, that would be cool to have. 
I'll have a look. Maybe it is easy to implement.

**Comment by JuergenGutsch** [comment]
Hey @snebjorn 
I'm really sorry for the late answer.
If I understand it right, this is a feature of graphql-net upon the schema implementation of this library.
Since I use graphql-dotnet (https://github.com/graphql-dotnet/graphql-dotnet) I need to extend their schema. 

I would say this feature is super cool, but it is not in the scope of this middleware. I'd propose to place this issue in the graphql-dotnet repository: https://github.com/graphql-dotnet/graphql-dotnet
Once this is in this library, you can use this feature with the middleware as well.
